---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/kiroushi/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/development/github/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore_global
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  # - doxygen
  - composer
  - dockutil
  # - gettext
  # - gifsicle
  - git
  # - go
  # - gpg
  # - hub
  # - httpie
  # - iperf
  # - libevent
  # - sqlite
  - mas
  - mcrypt
  - nmap
  - node
  - nvm
  - php@7.2
  - ssh-copy-id
  # - cowsay
  # - readline
  - openssl
  # - pv
  - wget
  # - wrk
  - zsh
  - zsh-completions

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - appcleaner
  - bitwarden
  #- chromedriver
  #- docker
  #- dropbox
  #- firefox
  - google-chrome
  #- handbrake
  - iterm2
  #- licecap
  #- limechat
  #- macvim
  - microsoft-remote-desktop-beta
  #- sequel-pro
  #- skitch
  #- slack
  - spectacle
  - spotify
  #- sublime-text
  - teamviewer
  - telegram
  - the-unarchiver
  #- transmit
  #- vagrant
  - usb-overdrive
  - visual-studio-code
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 824183456, name: "Affinity Photo (1.6.7)" }
  - { id: 824171161, name: "Affinity Designer (1.6.1)" }

mas_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61353738633935656266376531623634303139323835303637393934623835653463366361323363
          3833636164383039616635613936626363366230373334620a303539613134646165643164343162
          38666266646262626465663161393762346438633630663638316538343466623639386634323638
          6162396265356238640a383166323731303662366230666261366430353561353434386637323632
          30623838343239623938653166343066666232613637663566623636316134626637

mas_signin_dialog: no

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendar
  - Siri
 
dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 2
  - name: Affinity Designer
    path: "/Applications/Affinity Designer.app"
    pos: 3
  - name: Affinity Photo
    path: "/Applications/Affinity Photo.app"
    pos: 4

fonts:
  - Convergence
  - Inconsolata
  - Josefin Sans
  - Lato
  - Noto Sans
  - Raleway
