---
- name: Download fonts from Google Fonts and unzip them to system fonts folder
  unarchive:
    src: "https://fonts.google.com/download?family={{ item | replace(' ', '+') }}"
    dest: /Library/Fonts
    remote_src: yes
    exclude: '*.txt'
  with_items: '{{ fonts }}'
  become: yes