---
- name: Download fonts from Google Fonts and unzip them to system fonts folder
  unarchive:
    src: "https://fonts.google.com/download?family={{ item | replace(' ', '+') }}"
    dest: /Library/Fonts
    remote_src: true
    exclude: '*.txt'
  with_items: '{{ fonts }}'
  become: true

- name: Download JetBrains mono
  unarchive:
    src: "https://download.jetbrains.com/fonts/JetBrainsMono-2.225.zip"
    dest: /Library/Fonts
    remote_src: true
    exclude: '*.txt'
  become: true

